name: Pysintaller Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependency env
        uses: actions/setup-python@v2
        with:
              python-version: '3.9.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
              architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
           sudo apt update
           sudo apt install  gir1.2-gtk-3.0 
           python -m pip install --upgrade pip
           HTSLIB_CONFIGURE_OPTIONS="--disable-lzma" pip install -r requirements.txt
   
      - name: Download latest macos binary
        run: curl -L  https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt_macos -o bin/osx/tinyt_macos
      
      - name: Download latest exe binary
        run: curl -L https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt.exe -o bin/win/tinyt.exe 
      
      - name: Download latest linux binary
        run: curl -L https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt_amd64 -o bin/linux/tinyt_amd64


      - name: Build
        run: sudo ./create_linux.bash && sudo chmod +x ./dist/Toblerone && sudo mv  ./dist/Toblerone ./dist/Toblerone_linux && sudo chmod +x ./dist/Toblerone_linux 

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/Toblerone_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js for dmg  
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install xz htslib
        run: |
          brew update
          brew install xz htslib

      - name: Install create-dmg
        run: |
           npm init -y
           npm install --global create-dmg

      - name: Install dependency env
        uses: actions/setup-python@v2
        with:
              python-version: '3.9.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
              architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install cython
           HTSLIB_CONFIGURE_OPTIONS="--disable-lzma" pip install -r requirements.txt 
      - name: Download latest macos binary
        run: curl -L https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt_macos -o bin/osx/tinyt_macos
      
      - name: Download latest exe binary
        run: curl -L https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt.exe -o bin/win/tinyt.exe 
      
      - name: Download latest linux binary
        run: curl -L  https://github.com/Oshlack/Toblerone/releases/latest/download/tinyt_amd64 -o bin/linux/tinyt_amd64
      
      - name: Build for mac
        run: python3 create_macos.py py2app && chmod +x ./dist/Toblerone.app 

      - name: Build dmg
        continue-on-error: true
        run: |
            cd ./dist/ 
            create-dmg 'Toblerone.app'

      - name: Rename dmg
        run: |
            echo "Previous step should passed with code signing error, exit(2)"
            cd ./dist/ && cp Toblerone*dmg Toblerone.dmg 
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/Toblerone.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
